### PR TITLE
Add support for disabling burn in protection.

### PR DESCRIPTION
**Pull request by MagneFire**
Checkout the main PR: https://github.com/AsteroidOS/asteroid-launcher/pull/69

Actually, it might be better to hide this option when `DeviceInfo.preferBurnInProtection` is set to false. If it is desired that this option is disabled by default (for example LCDs) then it doesn't make sense to show it anyway.

### CODE REVIEW

**Comment by MagneFire** [comment]
Had a discussion with @jrtberlin. We should change this implementation such that the burn in protection option should only be visible when actually needed (preferred).

This means that I'll change the option name from `DeviceInfo.preferBurnInProtection` to `DeviceInfo.needsBurnInProtection` and hide that option in the settings app when no burn in protection is needed (for LCDs).

**Comment by MagneFire** [comment]
The additional idea/change has now been applied, when a device doesn't need burn in protection techniques then the option isn't shown at all and disabled in asteroid-launcher.

**Comment by FlorentRevest** [comment]
Very cool, this is very often requested by our users :)

**Comment by MagneFire** [comment]
To be fair, I still need to disable burn in protection for watches that don't even need it. A quick glance at our supported watches indicates that the following don't need burn in protection (because they have an LCD): smelt, dory and tetra.

**Pull request merged**
